version: '3.8'

services:
  djangoapp:
    build: .
    container_name: shopboom_app
    volumes:
      - .:/app
      - prometheus_data:/app/metrics_data
    environment:
      - DATABASE_HOST=postgres_db
      - DATABASE_PORT=5432
      - DATABASE_NAME=ShopBoom
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=1
      - PROMETHEUS_MULTIPROC_DIR=/app/metrics_data
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin123
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    networks:
      - djanago_monitoring

  postgres_db:
    image: postgres:17
    container_name: postgres_db_django
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: ShopBoom
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - djanago_monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_django
    ports:
      - "9176:9090"
    volumes:
    - prometheus_data:/app/metrics_data
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - djanago_monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_django
    ports:
      - "3816:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - djanago_monitoring

volumes:
  prometheus_data:
  postgres_data:
  grafana_data:

networks:
  djanago_monitoring:
    driver: bridge
